FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_VECTOR_PMTILES_URL
ARG VITE_TERRAIN_PMTILES_URL
ARG VITE_MAP_INITIAL_LNG=36.8219
ARG VITE_MAP_INITIAL_LAT=-1.2921
ARG VITE_MAP_INITIAL_ZOOM=12

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY \
    VITE_VECTOR_PMTILES_URL=$VITE_VECTOR_PMTILES_URL \
    VITE_TERRAIN_PMTILES_URL=$VITE_TERRAIN_PMTILES_URL \
    VITE_MAP_INITIAL_LNG=$VITE_MAP_INITIAL_LNG \
    VITE_MAP_INITIAL_LAT=$VITE_MAP_INITIAL_LAT \
    VITE_MAP_INITIAL_ZOOM=$VITE_MAP_INITIAL_ZOOM

RUN npm run build

FROM nginx:1.29-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1/ || exit 1
